test:
  stage: test
  image: python:3.8.3-alpine
  script:
    - pip3 install flake8 flake8-quotes pep8-naming
    - flake8

deploy:
  stage: deploy
  environment: Production
  only:
    - master@iot-alliance/iota-app/iota-app-backend
  script:
    - gem install dpl
    - dpl --provider=heroku --app=iota-app-backend --api-key=$HEROKU_STAGING_API_KEY
