test:
  stage: test
  image: python:3.8.3-alpine
  script:
    - pip3 install flake8 flake8-quotes pep8-naming
    - flake8

deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  environment: Production
  only:
    - master@iot-alliance/iota-app/iota-app-backend
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml
    - rm /tmp/$CI_PIPELINE_ID.json